### ISSUE TITLE
Touch start coordinates

### ISSUE THREAD

**Issue by sodface** [TAAPArthur/libsgestures#4]
Hello, I hope your new year is going well!

I am still using this great software with no issues but I'm changing other components and in the process decided to also change how I'm using libsgestures.

I'd like to completely offload the gesture region detection to an external script. Currently, regions are set at compile time. I've accomplished this by monitoring both `gestureSelectMask` and `TouchStartMask` so I get two messages for each event, the touch start and then the final gesture.

I tried to figure out to include the touch down coordinates as part of the final gesture event but couldn't figure it out. If you have any suggestions I'd appreciate it. Thanks!

**Comment by TAAPArthur** [comment]
My year is going well. Hope yours is also.

`gestureSelectMask` dictates the events that will be broadcasted. By
default it is `GestureEndMask`. It sounds like you are listening on both
GestureEndMask and TouchStartMask.

>I tried to figure out to include the touch down coordinates as part of the
final gesture event but couldn't figure it out.

I'm not sure I follow. The end point is included in all gesture events (See
the `GestureEvent` struct or `dumpGesture` for an example). If you want a
position before the end of the gesture, maybe the `TouchEndMask` would help.

Also I've moved development for all my projects to [code](berghttps://
codeberg.org/TAAPArthur/sgestures). Feel free to migrate this issue there
if you want. Also if you could share how you  are using the project I may
be able to offer better advice.

**Comment by sodface** [comment]
Issue moved to [Codeberg.](https://codeberg.org/TAAPArthur/sgestures/issues/1)

**Comment by sodface** [comment]
Closing.
